name = "ParameterSchedulers"
uuid = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
authors = ["Kyle Daruwalla"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
title = "ParameterSchedulers.jl"

    [publish.html]
    css = "docs/custom.css"

        [publish.html.template]
        file = "docs/custom.mustache"

[targets]
test = ["Test"]
